"""Photography extracted from the 2026 mockup and the current evolveincorporated.com, renamed for SEO.
Licenses must be confirmed before production (several carry stock-photographer credits).
Generated by scripts/import-stock.py; edit alt text here if needed."""

STOCK_IMAGES = {
    "colocation-aisle-server-cabinets": {
        "file": "colocation-aisle-server-cabinets",
        "widths": [
            1067,
            1000,
            640
        ],
        "w": 1067,
        "h": 800,
        "alt": "Colocation data hall aisle between locked server cabinets with status lights"
    },
    "data-hall-corridor-white-cabinets": {
        "file": "data-hall-corridor-white-cabinets",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Bright data hall corridor lined with white server cabinets"
    },
    "technician-connecting-server-cable": {
        "file": "technician-connecting-server-cable",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Technician connecting a network cable to a server in a rack"
    },
    "electrician-testing-electrical-panel": {
        "file": "electrician-testing-electrical-panel",
        "widths": [
            902,
            640
        ],
        "w": 902,
        "h": 600,
        "alt": "Electrician in a hard hat testing an open electrical panel"
    },
    "operations-center-monitoring-screens": {
        "file": "operations-center-monitoring-screens",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 675,
        "alt": "Operator reviewing facility monitoring screens in an operations center"
    },
    "technician-generator-switchgear-panel": {
        "file": "technician-generator-switchgear-panel",
        "widths": [
            1024,
            1000,
            640
        ],
        "w": 1024,
        "h": 501,
        "alt": "Technician in a hi-vis vest checking a generator control panel"
    },
    "construction-team-reviewing-plans-hard-hats": {
        "file": "construction-team-reviewing-plans-hard-hats",
        "widths": [
            1138,
            1000,
            640
        ],
        "w": 1138,
        "h": 600,
        "alt": "Overhead view of a construction team in hard hats reviewing drawings"
    },
    "site-planning-review-hi-vis-engineers": {
        "file": "site-planning-review-hi-vis-engineers",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Two engineers in hi-vis vests reviewing plans on a job site"
    },
    "evolve-groundbreaking-ceremony-team": {
        "file": "evolve-groundbreaking-ceremony-team",
        "widths": [
            1320,
            1280,
            1000,
            640
        ],
        "w": 1320,
        "h": 990,
        "alt": "Evolve team with shovels at a data-center groundbreaking"
    },
    "facility-cable-tray-overhead": {
        "file": "facility-cable-tray-overhead",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Overhead cable tray and conduit inside a critical facility"
    },
    "technician-control-room-hard-hat": {
        "file": "technician-control-room-hard-hat",
        "widths": [
            1024,
            1000,
            640
        ],
        "w": 1024,
        "h": 540,
        "alt": "Technician in a hard hat working at control-room screens"
    },
    "network-operations-center-operator": {
        "file": "network-operations-center-operator",
        "widths": [
            1000,
            640
        ],
        "w": 1000,
        "h": 563,
        "alt": "Operator at a bank of monitoring displays in a network operations center"
    },
    "technicians-rooftop-cooling-units": {
        "file": "technicians-rooftop-cooling-units",
        "widths": [
            1024,
            1000,
            640
        ],
        "w": 1024,
        "h": 683,
        "alt": "Two technicians in hi-vis servicing rooftop cooling units"
    },
    "evolve-generator-enclosure": {
        "file": "evolve-generator-enclosure",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 900,
        "alt": "White Evolve-branded generator enclosure with intake louvers"
    },
    "data-center-construction-site-crew-sunset": {
        "file": "data-center-construction-site-crew-sunset",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Construction crew on a data-center site at sunset"
    },
    "cranes-over-data-center-building": {
        "file": "cranes-over-data-center-building",
        "widths": [
            1024,
            1000,
            640
        ],
        "w": 1024,
        "h": 596,
        "alt": "Two lattice cranes over a large data-center building under construction"
    },
    "tower-crane-data-center-construction": {
        "file": "tower-crane-data-center-construction",
        "widths": [
            1920,
            1280,
            1000,
            640
        ],
        "w": 3815,
        "h": 4769,
        "alt": "Tower crane against an overcast sky on a construction site"
    },
    "cell-tower-edge-site-sunset": {
        "file": "cell-tower-edge-site-sunset",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 607,
        "alt": "Telecommunications tower at an edge site at sunset"
    },
    "engineer-laptop-data-hall": {
        "file": "engineer-laptop-data-hall",
        "widths": [
            1920,
            1280,
            1000,
            640
        ],
        "w": 2560,
        "h": 1707,
        "alt": "Engineer with a laptop walking a bright data hall aisle"
    },
    "engineer-drafting-facility-drawings": {
        "file": "engineer-drafting-facility-drawings",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Engineer drafting facility drawings at a desk"
    },
    "preconstruction-blueprint-review-hard-hat": {
        "file": "preconstruction-blueprint-review-hard-hat",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Hands over blueprints beside a hard hat during preconstruction review"
    },
    "engineering-team-reviewing-drawings": {
        "file": "engineering-team-reviewing-drawings",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Engineering team marking up drawings at a table"
    },
    "steel-fabrication-hall": {
        "file": "steel-fabrication-hall",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 900,
        "alt": "Interior of a steel fabrication hall with overhead structure"
    },
    "texas-hill-country-site-landscape": {
        "file": "texas-hill-country-site-landscape",
        "widths": [
            1920,
            1280,
            1000,
            640
        ],
        "w": 2560,
        "h": 1920,
        "alt": "Open Texas hill-country landscape considered for development"
    },
    "team-inspecting-server-room": {
        "file": "team-inspecting-server-room",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Two people inspecting equipment in a server room"
    },
    "technician-servicing-server-rack": {
        "file": "technician-servicing-server-rack",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 801,
        "alt": "Technician kneeling to service equipment in a server rack"
    },
    "technicians-tablet-server-room": {
        "file": "technicians-tablet-server-room",
        "widths": [
            1920,
            1280,
            1000,
            640
        ],
        "w": 2560,
        "h": 1707,
        "alt": "Two technicians reviewing a tablet during server-room maintenance"
    },
    "engineer-walking-building-shell": {
        "file": "engineer-walking-building-shell",
        "widths": [
            1545,
            1280,
            1000,
            640
        ],
        "w": 1545,
        "h": 789,
        "alt": "Engineer with a laptop walking through an unfinished building shell"
    },
    "server-room-corridor-racks": {
        "file": "server-room-corridor-racks",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 801,
        "alt": "Server room corridor between rows of equipment racks"
    },
    "server-cabinets-data-center": {
        "file": "server-cabinets-data-center",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 947,
        "alt": "Rows of server cabinets in a data center"
    },
    "river-landscape-site-development": {
        "file": "river-landscape-site-development",
        "widths": [
            1920,
            1280,
            1000,
            640
        ],
        "w": 1920,
        "h": 2560,
        "alt": "River and open land near a development site"
    },
    "large-data-hall-rows": {
        "file": "large-data-hall-rows",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 900,
        "alt": "Large data hall with long rows of equipment"
    },
    "data-center-foundation-rebar-construction": {
        "file": "data-center-foundation-rebar-construction",
        "widths": [
            1000,
            640
        ],
        "w": 1000,
        "h": 521,
        "alt": "Crew placing rebar for a data-center foundation"
    },
    "data-hall-monitoring-desk-commissioning": {
        "file": "data-hall-monitoring-desk-commissioning",
        "widths": [
            1920,
            1280,
            1000,
            640
        ],
        "w": 2560,
        "h": 1707,
        "alt": "Two engineers at a monitoring desk inside a data hall"
    },
    "turbine-generator-hall": {
        "file": "turbine-generator-hall",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 572,
        "alt": "Turbine generator inside an industrial power hall"
    },
    "technician-server-rack-service-cart": {
        "file": "technician-server-rack-service-cart",
        "widths": [
            1920,
            1280,
            1000,
            640
        ],
        "w": 2000,
        "h": 1333,
        "alt": "Technician with a service cart working at open server racks"
    },
    "technicians-open-server-rack": {
        "file": "technicians-open-server-rack",
        "widths": [
            1920,
            1280,
            1000,
            640
        ],
        "w": 2560,
        "h": 1440,
        "alt": "Two technicians examining equipment in an open server rack"
    },
    "network-rack-cabling": {
        "file": "network-rack-cabling",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 675,
        "alt": "Structured network cabling on data-center racks"
    },
    "technician-radio-control-panel": {
        "file": "technician-radio-control-panel",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Technician with a radio at an electrical control panel"
    },
    "white-server-rack-rows-data-hall": {
        "file": "white-server-rack-rows-data-hall",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 675,
        "alt": "Data hall with multiple rows of white server racks"
    },
    "technicians-laptop-server-room": {
        "file": "technicians-laptop-server-room",
        "widths": [
            1920,
            1280,
            1000,
            640
        ],
        "w": 8688,
        "h": 5792,
        "alt": "Two technicians analyzing a laptop between server racks"
    },
    "project-team-reviewing-plans": {
        "file": "project-team-reviewing-plans",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 800,
        "alt": "Project team reviewing plans with a hard hat on the table"
    },
    "power-lines-solar-sunset": {
        "file": "power-lines-solar-sunset",
        "widths": [
            1200,
            1000,
            640
        ],
        "w": 1200,
        "h": 651,
        "alt": "Transmission lines and solar panels at sunset"
    },
    "diesel-generator-engine": {
        "file": "diesel-generator-engine",
        "widths": [
            1600,
            1280,
            1000,
            640
        ],
        "w": 1600,
        "h": 1200,
        "alt": "Red diesel generator engine inside an enclosure"
    }
}
